use_frameworks!

target 'GTProgressBar_Example' do
  platform :ios, '9.0'
  pod 'GTProgressBar', :path => '../'

  target 'GTProgressBar_Tests' do
    inherit! :search_paths
    pod 'Nimble', '9.2.0'
  end
end
