use_frameworks!

target 'GTProgressBar_Example' do
  pod 'GTProgressBar', :path => '../'

  target 'GTProgressBar_Tests' do
    inherit! :search_paths
    pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git', :commit => 'db706fc'
  end
end
